### ISSUE TITLE
Implement of scroll depth custom code

### ISSUE THREAD

**Issue by techjoyment** [WodenWang820118/ng-gtm-site#109]
Hi
What should I set in trigger for scroll tracking custom HTML code? Do I need to set any variable?

**Comment by WodenWang820118** [comment]
Hi @techjoyment ,
Welcome. There should be two triggers to be used with custom scroll code:
1. `Window Loaded` to wait until all lazy loading components are fully loaded on the landing page. Please refer to the [documentation](https://support.google.com/tagmanager/answer/7679319?hl=en) for more information.
2. Built-in [history change trigger](https://support.google.com/tagmanager/answer/7679322?hl=en) when directing to other routes in SPA.

You may refer to the workspace file and import it to your GTM. Let me know if you have more questions.
