### ISSUE TITLE
Scroll tracking code

### ISSUE THREAD

**Issue by techjoyment** [WodenWang820118/ng-gtm-site#110]
Hi
Your code has a issue with pages with no scroll or little scroll. In these pages all/most scroll threshold are fire even without actual scroll. Can you fix these issue by adding this solution to the code?:
https://www.simoahava.com/analytics/customize-scroll-depth-trigger/

**Comment by WodenWang820118** [comment]
Hi, @techjoyment 
I'll have a look. The code, yes, fires scroll data if there's no need to scroll the page. For example, the landing page would have 100% scrolled by default. Thanks.

**Comment by WodenWang820118** [comment]
Hi, @techjoyment 
I've implemented a solution. It needs three parts.
1. The custom script introduced before
2. It needs a way to detect when the page is fully loaded in terms of SPA. In the codebase, I use a loading div to improve initial loading performance. Based on `ngAfterViewCheckekd` life cycle, I can signify and push another event to the dataLayer.
3. The solution provided by Simo Ahava is employed to ensure meaningful scroll tracking.

Thank you for raising the issue. For details, please refer to the newly uploaded GTM configuration file.

**Comment by techjoyment** [comment]
Thanks for making changes.
I only want to use your scroll solution not whole file. How can I use and implement new scripts in my GTM container?

**Comment by WodenWang820118** [comment]
Hi, @techjoyment 
Thank you for reaching out. In terms of GTM, please use [Custom HTML tag](https://support.google.com/tagmanager/answer/6107167?hl=en) to put my implementation into it and use the trigger accordingly. Please refer to the new documentation (README.md).

Another thing. If you have further questions, please reopen with comment. Otherwise, I might be able to read Email notifications. Thanks.

Best,
Guan Xin Wang

**Comment by techjoyment** [comment]
Can't find any differences between new code and previous one.

**Comment by WodenWang820118** [comment]
The code doesn't change, but there's another amendment built on top of it. Please refer to the GTM JSON file at the root directory and import it to you workspace to find out how I tackle the issue. I'll close the issue. Thanks.
